import { Client } from '../client/client';
import { Fournisseur } from '../fournisseur/fournisseur';
import { User } from '../user/user';

export class InfosCard {
    id: number;
    intituleCarte: string;
    ica: string;
    typeProduit: string;
    bin: string;
    scheime: string;
    paiement: string;
    puce: boolean;
    piste: boolean;
    fabriquantPuce: string;
    capacitePuce: string;
    dateExpPuce: Date;
    masquePuce: string;
    typePuce: string;
    refVisaMc: string;
    couleurRecto: string;
    couleurVerso: string;
    effetsSpeciaux: string;
    autresEffets: string;
    panneauSignature: string;
    finition: string;
    hologramme: string;
    laminat: string;
    typeImpRecto: string;
    couleurImp: string;
    dateReceptionFV: Date;
    dateEnvoiVisuelFr: Date;
    dateReception: Date;
    refVisuel: string;
    dateEnvoiPdfClt: Date;
    dateEnvoiPdfCltVr1: Date;
    dateEnvoiPdfCltVr2: Date;
    dateEnvoiPdfCltVr3: Date;
    dateValidationClt: Date;
    dateReceptionChromalin: Date;
    dateSoumissionVisaMc: Date;
    dateResoumissionVisaMc: Date;
    numSoumission: number;
    dateApprobationVisaMc: Date;
    dateBonCdeS2M: Date;
    numBonCdeS2M: number;
    quantite: number;
    dateEnlevement: Date;
    dateReceptionS2M: Date;
    facturationLivraison: boolean;
    numFacture: number;
    dateFacture: Date;
    contact: boolean;
    contactLess: boolean;
    dda: boolean;
    sda: boolean;
    cda: boolean;
    commentaire: string;
    user: User;
    client: Client = new Client();
    fournisseur: Fournisseur = new Fournisseur();
}